#pragma once

/* Test Vendor/Product IDs (Matter lab defaults). */
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8000

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "CJC"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Magic Button"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_PRODUCT_REVISION_STRING "1.0"
